/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CardBack: typeof import('./src/components/projects/CardBack.vue')['default']
    CardFront: typeof import('./src/components/projects/CardFront.vue')['default']
    Home: typeof import('./src/components/home/index.vue')['default']
    Image: typeof import('primevue/image')['default']
    NavButton: typeof import('./src/components/NavButton.vue')['default']
    Projects: typeof import('./src/components/projects/index.vue')['default']
  }
}
